name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_ADMIN_EMAILS: ${{ secrets.APP_ADMIN_EMAILS }}
          envkey_APP_MAIL_SOURCE: ${{ secrets.APP_MAIL_SOURCE }}
          envkey_AWS_SES_ACCESS_KEY: ${{ secrets.AWS_SES_ACCESS_KEY }}
          envkey_AWS_SES_SECRET_ACCESS_KEY: ${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}
          envkey_APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
          file_name: .env.local
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
