name: test-integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NEXT_PUBLIC_DEV_APP_ADMIN_EMAIL: ${{ secrets.NEXT_PUBLIC_DEV_APP_ADMIN_EMAIL }}
          envkey_APP_ADMIN_EMAIL: ${{ secrets.APP_ADMIN_EMAILS }}
          envkey_APP_MAIL_SOURCE: ${{ secrets.APP_MAIL_SOURCE }}
          envkey_AWS_SES_ACCESS_KEY: ${{ secrets.AWS_SES_ACCESS_KEY }}
          envkey_AWS_SES_SECRET_ACCESS_KEY: ${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}
          envkey_APP_ID: ${{ secrets.APP_ID }}
          file_name: .env.local
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Unit tests
        run: yarn test
      - name: Integration tests
        run: docker-compose up --build --quiet-pull --exit-code-from integration